### ISSUE TITLE
Preparing RC2

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3466]
Not really an issue but it's easier to keep track of the progress.
To release 1.8.2-RC2 we need to:

# TODO **Before** release

- [x] Change the version number on all the installers, with and without jdk
  - [x] windows installer
  - [x] linux .deb installer
  - [x] macOS .dmg
- [x] Fix all the models in `Library models` and `Plugin models` that do not compile anymore or have warnings

# TODO **After** release

- [x] Once compiled, add it to [gama.resources](https://github.com/gama-platform/gama.resources/releases) (mostly useful for [`brew`](https://github.com/Homebrew/homebrew-cask/pull/124797#issuecomment-1149299793) without the `pre-release` tag)
- [x] Update hosted installers, with and without jdk
  - [x] linux aur [w/ JDK](https://aur.archlinux.org/packages/gama-platform-jdk) and [w/o JDK](https://aur.archlinux.org/packages/gama-platform)
  - [x] macOS brew package [w/ JDK](https://formulae.brew.sh/cask/gama-jdk) and [w/o JDK](https://formulae.brew.sh/cask/gama) -> [PR here](https://github.com/Homebrew/homebrew-cask/pull/128414)
- [x] Freeze the documentation as 1.8.2-RC2 
- [x] Update the download links on the website
- [x] Test the installers on all platforms:
  - [x] windows 
  - [x] macOS
  - [x] macOS M1
  - [x] linux
- [x] Test brew installation:
  - [x] macOS
  - [x] macOS M1 
- [x] Run gama from the zip files:
  - [x] windows
  - [x] linux
